hostname_base="Generic Arma3"
hostname_id1=' Antistasi Altis'
hostname_id2=' HC1'
hostname_id3=' HC2'
hostname_id4=' HC3'

# build modlist

mods=""
servermods=""

while read line; do
	apptype=$(echo $line | awk '{ printf "%s", $3 }')
	appname=$(echo $line | awk '{ printf "%s", $1 }')
	appkey=$(echo $line | awk -v var=$(( $serverid + 3 )) '{ printf "%s", $var }')

	#echo "appname ${appname} appkey ${appkey} apptype ${apptype}"

	if [ "${apptype}" = "mod" ] && [ "${appkey}" = "1" ]; then
		mods=${mods}"_mods/@"${appname}";"
	fi

  if [ "${apptype}" = "smod" ] && [ "${appkey}" = "1" ]; then
    servermods=${servermods}"_mods/@"${appname}";"
  fi

done < ${basepath}/scripts/modlist.inp

export mods=$mods
export servermods=$servermods

# make hostname
case "$serverid" in
1)
hostname=${hostname_base}${hostname_id1}
;;
2)
hostname=${hostname_base}${hostname_id2}
;;
3)
hostname=${hostname_base}${hostname_id3}
;;
4)
hostname=${hostname_base}${hostname_id4}
;;
esac

# generate cfg-file
echo "//-------------------------------------
//DO NOT MODIFY THIS FILE, IT IS GENERATED BY A SCRIPT
//modify a3common.cfg and a3indi\[i\].cfg  instead.
//
//***Start of scripted part***
//

hostname = \"${hostname}\";

//
//***End of Scripted part***
//
//------------------------------------
//*** a3common.cfg ***" > $config
chown ${useradm}:${profile} $config
chmod 664 $config
#
cat ${cfg_dir}/a3common.cfg >> ${config}
echo "//
//------------------------------------
//***a3indi${serverid}.cfg ***
//" >> ${config}
cat ${cfg_dir}/a3indi${serverid}.cfg >> ${config}

# make symlinks to the keys
find ${basepath}/a3srv${serverid}/keys/ -maxdepth 1 -type l -delete
ln -s ${basepath}/a3master/keys/a3.bikey ${basepath}/a3srv${serverid}/keys/
while read line; do
	apptype=$(echo $line | awk '{ printf "%s", $3 }')
  appname=$(echo $line | awk '{ printf "%s", $1 }')
  appkey=$(echo $line | awk -v var=$(( $serverid + 3 )) '{ printf "%s", $var }' )
  #echo "appkey = ${appkey} for ${appname}"

    if [ "${serverid}" == "1" ] && [ "${apptype}" != "smod" ] && [ "${appkey}" = "1" ]; then
			#echo " ... ${appname}-key on server #${serverid}"
			ln -sf ${basepath}/a3master/_mods/@${appname}/*key*/*.bikey ${basepath}/a3srv${serverid}/keys/
    fi
done < ${basepath}/scripts/modlist.inp
